# Generated by Django 5.2.11 on 2026-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(help_text='Student roll number', max_length=30, null=True, unique=True),
        ),
    ]
