# Generated by Django 5.2.9 on 2025-12-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='security_references/'),
        ),
    ]
