# Generated by Django 5.2.9 on 2025-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='latitude',
            field=models.FloatField(default=12.9716, help_text='Class Location Latitude'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='longitude',
            field=models.FloatField(default=77.5946, help_text='Class Location Longitude'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='radius_meters',
            field=models.IntegerField(default=200, help_text='Allowed radius in meters'),
        ),
    ]
