# Generated by Django 5.2.9 on 2026-02-11 06:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_courseenrollment_and_more'),
        ('accounts', '0002_alter_user_options_alter_subject_staff_and_more'),
        ('attendance', '0001_initial'),
        ('profiles', '0002_hodprofile_alter_facultyprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('SPORTS', 'Sports Activity'), ('OUTDOOR', 'Outdoor Activity'), ('EXTRA', 'Extra Curricular'), ('MEDICAL', 'Medical Leave'), ('OTHER', 'Other')], max_length=10)),
                ('reason', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Face recognition confidence score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='allocation',
            field=models.ForeignKey(blank=True, help_text="Links to the faculty's subject allocation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.subjectallocation'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.course'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Laboratory'), ('TUTORIAL', 'Tutorial'), ('PRACTICAL', 'Practical')], default='LECTURE', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['staff', 'hod']}, on_delete=django.db.models.deletion.CASCADE, related_name='started_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance_status_a068a7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'student'], name='attendance_session_8e0013_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['is_active', 'session_date'], name='attendance__is_acti_e1d890_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['teacher', 'is_active'], name='attendance__teacher_50430f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_date'], name='attendance__session_6d407e_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('teacher',), name='single_active_session_per_teacher'),
        ),
        migrations.AlterModelTable(
            name='attendancerecord',
            table='attendance',
        ),
        migrations.AlterModelTable(
            name='attendancesession',
            table='attendance_sessions',
        ),
        migrations.AddField(
            model_name='permission',
            name='granted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['hod', 'staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='profiles.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['student', 'date'], name='permissions_student_94438a_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['status'], name='permissions_status_f0891e_idx'),
        ),
    ]
