# Generated by Django 5.2.9 on 2025-12-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_captures/'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='gps_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20),
        ),
    ]
