# Generated by Django 5.2.11 on 2026-02-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocation', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='coursedepartment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_departments', to='academics.course'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'hod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_departments', to='academics.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='course_department',
            field=models.ForeignKey(help_text='Which Course-Department combination (e.g., BTech-CSE)', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.coursedepartment'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='section',
            field=models.ForeignKey(help_text='Which section the student belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='student_allocations', to='academics.section'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.course'),
        ),
        migrations.AddField(
            model_name='section',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(help_text='Which course (BTech/MTech/PhD)', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(help_text='Which department (CSE/ECE/AI/VLSI)', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(help_text='Which semester', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='profiles.facultyprofile'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='section',
            field=models.ForeignKey(help_text='Which section this faculty teaches (Course + Dept + Year + Section)', on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='academics.section'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='coursedepartment',
            unique_together={('course', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('course', 'academic_year', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course_department', 'academic_year', 'year', 'section_letter')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('faculty', 'subject', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectenrollment',
            unique_together={('student', 'subject')},
        ),
    ]
