# Generated by Django 5.2.9 on 2025-12-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='profiles.facultyprofile'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('faculty', 'subject', 'semester')},
        ),
    ]
